image: golang

definitions:
  steps:
#    - step: &unit
#        name: unit tests
#        script:
    - step: &lint
        name: linting
        script:
          - source bitbucket-pipelines-go.sh
          - go get -u golang.org/x/lint/golint
          - go list ./... | grep -v /vendor/ | xargs -L1 golint -set_exit_status

pipelines:
  default:
    - parallel:
       - step: *lint
