image: golang

definitions:
  steps:
    - step: &unit
        name: unit tests
        script:
          - go test ./...
    - step: &lint
        name: linting
        script:
          - go get -u golang.org/x/lint/golint
          - golint -set_exit_status ./...

pipelines:
  default:
    - parallel:
       - step: *unit
       - step: *lint
