image: python:2.7

definitions:
  steps:
    - step: &unit
        name: unit tests
        caches:
          - pip
        script:

        artifacts:
          - htmlcov/**
    - step: &lint
        name: linting
        caches:
          - pip
        script:


pipelines:
  default:
    - parallel:
       - step: *lint
       - step: *unit
